tap "buo/cask-upgrade"
tap "derailed/k9s"
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/services"
tap "kubefirst/tools"
tap "linzeyan/tools"
tap "rs/tap"
# Run your GitHub Actions locally
brew "act"
# Simple, modern, secure file encryption
brew "age"
# General-purpose data compression with high compression ratio
brew "xz"
# New file format for still image compression
brew "jpeg-xl"
# Codec library for encoding and decoding AV1 video streams
brew "aom"
# GitOps Continuous Delivery for Kubernetes
brew "argocd"
# Tool for generating GNU Standards-compliant Makefiles
brew "automake"
# Utility to encode and decode base91 files
brew "base91"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Programmable completion for Bash 3.2
brew "bash-completion"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Cryptography and SSL/TLS Toolkit
brew "openssl@3"
# Parser generator
brew "bison"
# GNU internationalization (i18n) and localization (l10n) library
brew "gettext"
# Core application library for C
brew "glib"
# Ruby environment tool
brew "chruby"
# Formatting tools for C, C++, Obj-C, Java, JavaScript, TypeScript
brew "clang-format"
# Library for command-line editing
brew "readline"
# Cloudflare Tunnel client (formerly Argo Tunnel)
brew "cloudflared"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# JSON, YAML, TOML, XML, and CSV query and modification tool
brew "dasel"
# CLI tool to run policies against Kubernetes manifests YAML files or Helm charts
brew "datree"
# Perform a dhcp-request to check whether a dhcp-server is running
brew "dhcping"
# Tool for exploring each layer in a docker image
brew "dive"
# Synchronize your DNS to multiple providers from a simple DSL
brew "dnscontrol"
# Pack, ship and run any application as a lightweight container
brew "docker"
# .NET Core
brew "dotnet"
# Program that can automate interactive applications
brew "expect"
# Stack trace visualizer
brew "flamegraph"
# Terminal JSON viewer
brew "fx"
# GNU compiler collection
brew "gcc"
# Library for encoding and decoding .avif files
brew "libavif"
# Graphics library to dynamically manipulate images
brew "gd"
# GNU database manager
brew "gdbm"
# Toolkit for image loading and pixel buffer manipulation
brew "gdk-pixbuf"
# Distributed revision control system
brew "git"
# Render markdown on the CLI
brew "glow"
# Validating, recursive, caching DNS resolver
brew "unbound"
# GNU Transport Layer Security (TLS) Library
brew "gnutls"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Generate introspection data for GObject libraries
brew "gobject-introspection"
# Fast linters runner for Go
brew "golangci-lint"
# Deliver Go binaries as fast and easily as possible
brew "goreleaser"
# Terminal based graphical activity monitor inspired by gtop and vtop
brew "gotop"
# Image manipulation
brew "netpbm"
# OpenType text shaping engine
brew "harfbuzz"
# Framework for layout and rendering of i18n text
brew "pango"
# Library to render SVG files using Cairo
brew "librsvg"
# Graph visualization software from AT&T and Bell Labs
brew "graphviz"
# Next generation open source RPC library and framework
brew "grpc"
# Kubernetes package manager
brew "helm"
# HTTP load generator, ApacheBench (ab) replacement
brew "hey"
# Improved top (interactive process viewer)
brew "htop"
# Configurable static site generator
brew "hugo"
# Tools and libraries to manipulate images in many formats
brew "imagemagick"
# CLI wrapper for basic network utilities on macOS - ip command
brew "iproute2mac"
# Manage your Java environment
brew "jenv"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Little helper to run CNCF's k3s in Docker
brew "k3d"
# Modern load testing tool, using Go and JavaScript
brew "k6"
# Kubernetes CLI To Manage Your Clusters In Style!
brew "k9s"
# Command-line tool to kill processes listening on a specific port
brew "killport"
# Run local Kubernetes cluster in Docker
brew "kind"
# Tool to move from `docker-compose` to Kubernetes
brew "kompose"
# CLI tool to discover unused Kubernetes resources
brew "kor"
# Static analysis tool for Kubernetes YAML files and Helm charts
brew "kube-linter"
# KubeConfig Manager
brew "kubecm"
# Image processing and image analysis library
brew "leptonica"
# Multi-format archive and compression library
brew "libarchive"
# Portable Foreign Function Interface library
brew "libffi"
# C library SSHv1/SSHv2 client and server protocols
brew "libssh"
# YAML Parser
brew "libyaml"
# Tools for zmodem/xmodem/ymodem file transfer
brew "lrzsz"
# Fast, async, resource-friendly link checker
brew "lychee"
# Easily convert Marp Markdown files into static HTML/CSS, PDF, PPT and images
brew "marp-cli"
# Mac App Store command-line interface
brew "mas"
# Scalable distributed version control system
brew "mercurial"
# Like sed, awk, cut, join & sort for name-indexed data such as CSV
brew "miller"
# Simple tool to make locally trusted development certificates
brew "mkcert"
# Port scanning utility for large networks
brew "nmap"
# Manage multiple Node.js versions
brew "nvm"
# Command-line Git information tool
brew "onefetch"
# Open Fortinet client for PPP+SSL VPN tunnel services
brew "openfortivpn"
# Development kit for the Java programming language
brew "openjdk"
# Swiss-army knife of markup format conversion
brew "pandoc"
# PDF rendering library (based on the xpdf-3.0 code base)
brew "poppler"
# Tool for visualizing differences between two pdf files
brew "pdf-diff"
# Pinentry for GPG on Mac
brew "pinentry-mac"
# Tool for creating isolated virtual python environments
brew "virtualenv"
# Framework for managing multi-language pre-commit hooks
brew "pre-commit"
# Go support for Google's protocol buffers
brew "protoc-gen-go"
# Protoc plugin that generates code for gRPC-Go clients
brew "protoc-gen-go-grpc"
# Cloud native development platform
brew "pulumi"
# Parse HTML at the command-line
brew "pup"
# Interpreted, interactive, object-oriented programming language
brew "python@3.9"
# Software environment for statistical computing
brew "r"
# Utility that provides fast incremental file transfer
brew "rsync"
# Install Ruby, JRuby, Rubinius, TruffleRuby, or mruby
brew "ruby-install"
# Fast and accurate code counter with complexity and COCOMO estimates
brew "scc"
# Shell Script Compiler
brew "shc"
# HTTP regression testing and benchmarking utility
brew "siege"
# Terminal based presentation tool
brew "slides"
# Editor of encrypted files
brew "sops"
# Crypto and x509 Swiss-Army-Knife
brew "step"
# Tail multiple Kubernetes pods & their containers
brew "stern"
# Easiest, most secure way to use WireGuard and 2FA
brew "tailscale"
# Traceroute implementation using TCP packets
brew "tcptraceroute"
# OCR (Optical Character Recognition) engine
brew "tesseract"
# Free software distribution for the TeX typesetting system
brew "texlive"
# Simplified and community-driven man pages
brew "tldr"
# Terminal multiplexer
brew "tmux"
# Anonymizing overlay network for TCP
brew "tor"
# HTTP load testing tool and library
brew "vegeta"
# Internet file retriever
brew "wget"
# Tools for the WireGuard secure network tunnel
brew "wireguard-tools"
# HTTP benchmarking tool
brew "wrk"
# Process YAML, JSON, XML, CSV and properties documents from the CLI
brew "yq"
# UNIX shell (command interpreter)
brew "zsh"
# Terraform
brew "hashicorp/tap/terraform"
brew "kubefirst/tools/kubefirst"
brew "linzeyan/tools/ops-cli"
# JSON Aggregation CLI
brew "rs/tap/jaggr"
# iTerm2 expvar/JSON monitoring tool
brew "rs/tap/jplot"
# JDK from the Java User Group (JUG)
cask "adoptopenjdk"
# GraphQL client
cask "altair-graphql-client"
# Transfer files from and to an Android smartphone
cask "android-file-transfer", args: { appdir: "/Applications" }
# Redis desktop manager
cask "another-redis-desktop-manager"
# Two-factor authentication software
cask "authy", args: { appdir: "/Applications" }
# Data management tool that enables working with SQL Server
cask "azure-data-studio"
# Macbook | Clock, right on the touch bar
cask "clock-bar"
# Free app that makes your Internet safer
cask "cloudflare-warp"
# Server and cloud storage browser
cask "cyberduck"
# App for note taking, organizing, task lists, and archiving
cask "evernote", args: { appdir: "/Applications" }
# Web browser
cask "firefox", args: { appdir: "/Applications" }
# Developer targeted fonts with a high number of glyphs
cask "font-fira-code-nerd-font"
# Web browser
cask "google-chrome", args: { appdir: "/Applications" }
# Set of tools to manage resources and applications hosted on Google Cloud
cask "google-cloud-sdk"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2", args: { appdir: "/Applications" }
# Application to spoof your iOS, iPadOS or iPhoneSimulator device location
cask "locationsimulator"
# Interactive tool for analyzing MongoDB data
cask "mongodb-compass"
# Cross-platform MQTT 5.0 Desktop Client
cask "mqttx"
# Replacement for Docker Desktop
cask "orbstack"
# HTTP debugging proxy
cask "proxyman"
# Data science software focusing on R and Python
cask "rstudio"
# MySQL/MariaDB database management
cask "sequel-ace"
# Snip or pin screenshots
cask "snipaste", args: { appdir: "/Applications" }
# IDE, client, and GUI for MongoDB
cask "studio-3t"
# Text editor for code, markup and prose
cask "sublime-text"
# Desktop client for Telegram messenger
cask "telegram-desktop"
# Disposable email client
cask "tempbox"
# Unpacks archive files
cask "the-unarchiver", args: { appdir: "/Applications" }
# Free and open-source OpenVPN client
cask "tunnelblick"
# Development environment
cask "vagrant"
# Open-source code editor
cask "visual-studio-code"
# Multimedia player
cask "vlc", args: { appdir: "/Applications" }
# Network protocol analyzer
cask "wireshark"
mas "AdBlocker", id: 1018301773
mas "Amphetamine", id: 937984704
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Microsoft Remote Desktop", id: 1295203466
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
vscode "adamhartford.vscode-base64"
vscode "adpyke.codesnap"
vscode "ahmadalli.vscode-nginx-conf"
vscode "be5invis.toml"
vscode "bierner.markdown-mermaid"
vscode "bierner.markdown-preview-github-styles"
vscode "bpruitt-goddard.mermaid-markdown-syntax-highlighting"
vscode "christian-kohler.path-intellisense"
vscode "cipchk.zh-hans-tt-hant-vscode"
vscode "dustypomerleau.rust-syntax"
vscode "eamodio.gitlens"
vscode "EditorConfig.EditorConfig"
vscode "esbenp.prettier-vscode"
vscode "ezforo.copy-relative-path-and-line-numbers"
vscode "formulahendry.code-runner"
vscode "foxundermoon.shell-format"
vscode "GitHub.copilot"
vscode "GitHub.copilot-chat"
vscode "golang.go-nightly"
vscode "googlecloudtools.cloudcode"
vscode "GraphQL.vscode-graphql"
vscode "GraphQL.vscode-graphql-syntax"
vscode "Gruntfuggly.todo-tree"
vscode "hashicorp.hcl"
vscode "hashicorp.terraform"
vscode "hediet.vscode-drawio"
vscode "huacnlee.autocorrect"
vscode "inferrinizzard.prettier-sql-vscode"
vscode "jebbs.plantuml"
vscode "jinliming2.vscode-go-template"
vscode "kejun.devtoys"
vscode "kisstkondoros.vscode-gutter-preview"
vscode "llvm-vs-code-extensions.vscode-clangd"
vscode "matt-meyers.vscode-dbml"
vscode "mdickin.markdown-shortcuts"
vscode "mhutchie.git-graph"
vscode "mikestead.dotenv"
vscode "ms-azuretools.vscode-docker"
vscode "MS-CEINTL.vscode-language-pack-zh-hant"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode.remote-explorer"
vscode "mushan.vscode-paste-image"
vscode "nhoizey.gremlins"
vscode "oderwat.indent-rainbow"
vscode "pomdtr.excalidraw-editor"
vscode "quicktype.quicktype"
vscode "RandomFractalsInc.vscode-data-preview"
vscode "redhat.vscode-xml"
vscode "redhat.vscode-yaml"
vscode "rust-lang.rust-analyzer"
vscode "serayuzgur.crates"
vscode "shardulm94.trailing-spaces"
vscode "streetsidesoftware.code-spell-checker"
vscode "TabNine.tabnine-vscode"
vscode "Tim-Koehler.helm-intellisense"
vscode "tombonnike.vscode-status-bar-format-toggle"
vscode "usernamehw.errorlens"
vscode "vscode-icons-team.vscode-icons"
vscode "yzane.markdown-pdf"
vscode "yzhang.markdown-all-in-one"
vscode "ZainChen.json"
vscode "zxh404.vscode-proto3"
