#!/usr/bin/env bash

set -e

if [ ! -f $HOME/install.bash ]; then
  echo "Downloading install.bash script..."
  curl -sSfL https://raw.githubusercontent.com/linzeyan/terminal_config/master/macos/install.bash -o $HOME/install.bash
fi

bash $HOME/install.bash
