#!/usr/bin/env bash

set -e
scriptName="$HOME/.__install.bash"

cleanup() {
  msg "cleanup $scriptName"
  rm -f $scriptName
}

trap cleanup EXIT INT TERM

rm -f $scriptName

echo "Downloading install.bash"
curl -sSfL https://raw.githubusercontent.com/linzeyan/terminal_config/master/macos/install.bash -o $scriptName

echo "Execute install.bash"
bash $scriptName
