[tools]
"aqua:imsnif/bandwhich" = "latest"
go = "1.26"
node = "22"
python = "3.12"
rust = "stable"
uv = "latest"
jq = "latest"
"aqua:boyter/scc" = "latest"
"aqua:o2sh/onefetch" = "latest"
"aqua:nektos/act" = "latest"
"aqua:mvdan/sh" = "latest"
age = "latest"
bat = "latest"
cloudflared = "latest"
dasel = "latest"
delta = "latest"
dive = "latest"
dust = "latest"
fd = "latest"
fx = "latest"
git-cliff = "latest"
glow = "latest"
golangci-lint = "latest"
goreleaser = "latest"
hadolint = "latest"
hugo = "latest"
k6 = "latest"
killport = "latest"
opentofu = "latest"
pandoc = "latest"
sampler = "latest"
sops = "latest"
step = "latest"
tmux = "latest"
websocat = "latest"
yq = "latest"
"aqua:maaslalani/slides" = "latest"
"aqua:tealdeer-rs/tealdeer" = "latest"
"aqua:ericchiang/pup" = "latest"
"github:StackExchange/dnscontrol" = "latest"
"cargo:flamegraph" = "latest"
