[tools]
"aqua:imsnif/bandwhich" = "latest"
go = "latest"
node = "22"
python = "3.12"
rust = "stable"
uv = "latest"
jq = "latest"
"aqua:boyter/scc" = "latest"
"aqua:o2sh/onefetch" = "latest"
"aqua:nektos/act" = "latest"
"aqua:mvdan/sh" = "latest"
age = "latest"
bat = "latest"
cloudflared = "latest"
dasel = "latest"
delta = "latest"
dive = "latest"
dust = "latest"
fd = "latest"
fx = "latest"
git-cliff = "latest"
glow = "latest"
golangci-lint = "latest"
goreleaser = "latest"
hadolint = "latest"
k6 = "latest"
killport = "latest"
opentofu = "latest"
pandoc = "latest"
sampler = "latest"
sops = "latest"
step = "latest"
tmux = "latest"
websocat = "latest"
yq = "latest"
"aqua:maaslalani/slides" = "latest"
"aqua:tealdeer-rs/tealdeer" = "latest"
"aqua:ericchiang/pup" = "latest"
"github:StackExchange/dnscontrol" = "latest"
"cargo:flamegraph" = "latest"
rtk = "latest"
hugo-extended = "0.148.2"
"aqua:junegunn/fzf" = "latest"
"aqua:ajeetdsouza/zoxide" = "latest"
"aqua:linebender/resvg" = "latest"
"aqua:sxyazi/yazi" = "latest"
"aqua:golangci/golangci-lint" = "latest"
"aqua:sharkdp/vivid" = "latest"
eza = "latest"
watchexec = "latest"
protobuf = "latest"
protoc-gen-go = "latest"
protoc-gen-go-grpc = "latest"
"npm:prettier" = "latest"
"npm:eslint" = "latest"
"npm:typescript" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:mvdan.cc/gofumpt" = "latest"
"go:github.com/openrdap/rdap/cmd/rdap" = "master"
"go:github.com/google/capslock/cmd/capslock" = "latest"
"go:golang.org/x/perf/cmd/benchstat" = "latest"
"go:golang.org/x/tools/cmd/deadcode" = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"go:golang.org/x/vuln/cmd/govulncheck" = "latest"
"go:gorm.io/gen/tools/gentool" = "latest"
"go:github.com/fullstorydev/grpcurl/cmd/grpcurl" = "latest"
"github:golang-migrate/migrate" = "latest"
"go:github.com/google/wire/cmd/wire" = "latest"
"aqua:mr-karan/doggo" = "latest"
"aqua:wagoodman/dive" = "latest"
"aqua:fastfetch-cli/fastfetch" = "latest"
"aqua:goreleaser/goreleaser" = "latest"
"aqua:pnpm/pnpm" = "latest"
"aqua:j178/prek" = "latest"
"aqua:phiresky/ripgrep-all" = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
"github:sheeki03/tirith" = "latest"
"aqua:aquasecurity/trivy" = "latest"
"aqua:trzsz/trzsz-ssh" = "latest"
"aqua:vi/websocat" = "latest"
"github:upx/upx" = "latest"
"github:mufeedvh/code2prompt" = "latest"
"github:sharkdp/diskus" = "latest"
"github:ouch-org/ouch" = "latest"
ast-grep = "latest"
carapace = "latest"
